from chunking.chunkers.json.JSON_chunker import SplitNode

DOCUMENT_PLAN_PAPER = SplitNode(
    name="complete_document",
    children=[

        # Metadata
        SplitNode(
            name="metadata",
            children=[
                SplitNode(
                    name="bibliographic_info",
                    fields=[
                        "title",
                        "authors",
                        "journal",
                        "year",
                        "doi",
                    ]
                ),
                SplitNode(
                    name="article_classification",
                    fields=[
                        "article_type",
                        "article_subtype",
                        "medical_specialty",
                        "keywords",
                        "language",
                    ]
                ),
                SplitNode(
                    name="administrative_info",
                    fields=[
                        "trial_registration",
                        "funding",
                        "conflicts_of_interest",
                    ]
                ),
            ]
        ),

        # Background
        SplitNode(
            name="background_and_objective",
            children=[
                SplitNode(
                    name="clinical_background",
                    fields=[
                        "condition_or_topic",
                        "clinical_background",
                    ]
                ),
                SplitNode(
                    name="objectives",
                    fields=[
                        "objectives",
                        "clinical_question",
                    ]
                ),
            ]
        ),

        # Methods
        SplitNode(
            name="methods",
            children=[
                SplitNode(
                    name="study_design_population",
                    fields=[
                        "study_design",
                        "population",
                    ]
                ),
                SplitNode(
                    name="interventions_comparators",
                    fields=[
                        "interventions",
                        "comparators",
                    ]
                ),
                SplitNode(
                    name="outcomes",
                    fields=[
                        "outcomes",
                    ]
                ),
                SplitNode(
                    name="analysis",
                    fields=[
                        "statistical_methods",
                        "follow_up",
                    ]
                ),
                SplitNode(
                    name="review_methods",
                    fields=[
                        "search_strategy",
                        "databases",
                        "n_studies_included",
                        "quality_assessment_tool",
                    ]
                ),
            ]
        ),

        # Results
        SplitNode(
            name="results",
            children=[
                SplitNode(
                    name="main_findings",
                    fields=["main_findings"]
                ),
                SplitNode(
                    name="safety_results",
                    fields=["safety_results"]
                ),
                SplitNode(
                    name="subgroup_analyses",
                    fields=["subgroup_analyses"]
                ),
                SplitNode(
                    name="secondary_results",
                    fields=["secondary_results"]
                ),
            ]
        ),

        # Discussion
        SplitNode(
            name="discussion_and_implications",
            children=[
                SplitNode(
                    name="interpretation",
                    fields=[
                        "interpretation",
                        "comparison_with_prior_evidence",
                    ]
                ),
                SplitNode(
                    name="clinical_practice_implications",
                    fields=[
                        "clinical_implications",
                        "practice_implications",
                    ]
                ),
                SplitNode(
                    name="limitations_strengths",
                    fields=[
                        "limitations",
                        "strengths",
                    ]
                ),
                SplitNode(
                    name="future_directions",
                    fields=[
                        "open_questions",
                        "future_directions",
                    ]
                ),
            ]
        ),

        # Clinical entities
        SplitNode(
            name="clinical_entities",
            children=[
                SplitNode(
                    name="diseases_and_conditions",
                    fields=["diseases_and_conditions"]
                ),
                SplitNode(
                    name="drugs_and_therapies",
                    fields=["drugs_and_therapies"]
                ),
                SplitNode(
                    name="biomarkers_and_genes",
                    fields=["biomarkers_and_genes"]
                ),
                SplitNode(
                    name="scales_and_classifications",
                    fields=["scales_and_classifications"]
                ),
                SplitNode(
                    name="key_numeric_data",
                    fields=["key_numeric_data"]
                ),
            ]
        ),

        # Tables + conclusions
        SplitNode(
            name="tables_and_conclusions",
            children=[
                SplitNode(
                    name="tables",
                    fields=["tables"]
                ),
                SplitNode(
                    name="conclusions",
                    fields=[
                        "main_conclusion",
                        "narrative_summary",
                    ]
                ),
            ]
        ),

        SplitNode(
            name="_usage",
            fields=["_usage"]
        ),
    ]
)